title: "Affiliates"
email: dampigbed@fanclub.pm
timezone: UTC
baseurl: "https://suisei880.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'meownime-1'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Meow
    display_name: Sal
    avatar: 'assets/images/sal.png'
    email: dampigbed@fanclub.pm
    web: https://suisei880.github.io
    twitter: https://twitter.com/airdrop434
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Social
social:
  instagram: https://www.instagram.com/hendra.1107/
  facebook: https://www.facebook.com/hendra.suryantara.1 
  twitter: https://twitter.com/airdrop434 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
